# Generated by Django 5.1.6 on 2025-03-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=100, verbose_name='senha'),
        ),
    ]
