# Generated by Django 5.1.6 on 2025-02-28 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cadastro_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
